version: '3.8'

services:
  bk25:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - BK25_MODEL=llama3.1:8b
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - bk25-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - bk25-network
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama-data:
    driver: local

networks:
  bk25-network:
    driver: bridge
